INSERT INTO shows (slug, name, description) VALUES
("24", "24", "Counterterrorism agent Jack Bauer races against the clock to stop terrorist attacks and save lives."),
("american_idol", "American Idol", "Aspiring singers compete for a record deal and a shot at stardom in this popular reality competition show."),
("buffy_the_vampire_slayer", "Buffy the Vampire Slayer", "A teenage girl is chosen to battle vampires, demons, and other supernatural forces in this cult classic."),
("criminal_minds", "Criminal Minds", "An elite team of FBI profilers analyze the country\'s most twisted criminal minds and try to anticipate their next moves."),
("csi", "CSI", "A team of forensic investigators in Las Vegas use science to solve crimes and bring criminals to justice."),
("curb_your_enthusiasm", "Curb Your Enthusiasm", "Comedian Larry David plays a fictionalized version of himself as he navigates his personal and professional life."),
("family_guy", "Family Guy", "The Griffin family and their friends get into hilarious hijinks and pop culture parodies in this animated sitcom."),
("friends", "Friends", "A group of friends in their 20s and 30s navigate life, love, and work in New York City."),
("fringe", "Fringe", "FBI agent Olivia Dunham investigates unexplained phenomena with the help of a mad scientist and his son."),
("game_of_thrones", "Game of Thrones", "Noble families in a fantasy world fight for control of the Seven Kingdoms and the Iron Throne."),
("grey_s_anatomy", "Grey\'s Anatomy", "Medical interns and residents at Seattle Grace Hospital juggle their personal and professional lives while dealing with life-and-death situations."),
("heroes", "Heroes", "A group of people discover they have superhuman abilities and must navigate a world that fears and misunderstands them."),
("how_i_met_your_mother", "How I Met Your Mother", "A man tells his children the story of how he met their mother and the hilarious hijinks he and his friends got into along the way."),
("lost_girl", "Lost Girl", "A succubus named Bo tries to discover the truth about her origins and navigate the world of fae politics."),
("modern_family", "Modern Family", "Three interconnected families in Los Angeles navigate the ups and downs of life and love in this mockumentary-style sitcom."),
("ncis", "NCIS", "The Naval Criminal Investigative Service solves crimes involving the U.S. Navy and Marine Corps with the help of its team of special agents."),
("prison_break", "Prison Break", "A man tries to help his brother escape from prison after he is wrongfully convicted of murder."),
("scrubs", "Scrubs", "A group of doctors and nurses navigate the ups and downs of life and work at a fictional hospital in California."),
("smallville", "Smallville", "A young Clark Kent navigates the challenges of adolescence while discovering his superhuman abilities and his destiny as Superman."),
("the_big_bang_theory", "The Big Bang Theory", "A group of socially awkward scientists and their neighbor navigate their personal and professional lives in Pasadena, California."),
("the_office_us", "The Office (US)", "Employees at the Dunder Mifflin paper company navigate the ups and downs of office life in this mockumentary-style sitcom."),
("the_sopranos", "The Sopranos", "A New Jersey mob boss tries to balance his criminal enterprise with his family life and struggles with mental health issues."),
("the_walking_dead", "The Walking Dead", "A group of survivors in a post-apocalyptic world overrun by zombies fight to stay alive and find a new home."),
("the_wire", "The Wire", "Police officers and drug dealers in Baltimore navigate a complex web of corruption and violence in this gritty crime drama."),
("true_blood", "True Blood", "A telepathic waitress in a Louisiana town discovers a world of vampires, werewolves, and other supernatural beings."),
("two_and_a_half_men", "Two and a Half Men", "A wealthy bachelor and his brother navigate the ups and downs of life with the help of his precocious nephew."),
("the_oc", "The OC", "A troubled teen from the wrong side of the tracks is taken in by a wealthy family in Orange County, California."),
("the_shield", "The Shield", "A corrupt police strike team in Los Angeles crosses the line between law enforcement and criminality in this intense drama."),
("the_west_wing", "The West Wing", "The White House staff and the President navigate the challenges of politics and policy in this acclaimed drama series."),
("top_gear", "Top Gear", "A trio of British car enthusiasts test drive the latest and greatest cars and engage in wacky stunts and challenges."),
("true_detective", "True Detective", "Two detectives investigate a series of interconnected crimes in Louisiana while struggling with their own personal demons."),
("weeds", "Weeds", "A suburban widow starts selling marijuana to make ends meet and gets caught up in a dangerous and hilarious world of drugs and crime."),
("deadwood", "Deadwood", "A lawless mining town in the American West is home to a colorful cast of characters in this gritty and realistic drama."),
("six_feet_under", "Six Feet Under", "A family runs a funeral home in Los Angeles while dealing with their own personal and professional struggles in this darkly comedic drama."),
("the_shows", "The Shows", "An anthology series that explores different themes and genres with each season, featuring an ensemble cast of talented actors."),
("dexter", "Dexter", "A blood-spatter analyst for the Miami police department moonlights as a vigilante serial killer who targets other murderers."),
("mad_men", "Mad Men", "Advertising executives on Madison Avenue navigate the changing social and cultural landscape of the 1960s in this stylish drama series."),
("breaking_bad", "Breaking Bad", "A high school chemistry teacher turns to cooking and selling methamphetamine to provide for his family after being diagnosed with cancer."),
("orange_is_the_new_black", "Orange is the New Black", "A privileged New Yorker adapts to life in a women's prison after being convicted of a decade-old crime."),
("the_blacklist", "The Blacklist", "An ex-government agent turns himself in and helps the FBI catch other criminals on his \"blacklist\" in exchange for immunity."),
("homeland", "Homeland", "A CIA agent becomes convinced that a recently freed American POW has been turned by al-Qaeda and poses a threat to national security."),
("the_killing", "The Killing", "Detectives investigate the murder of a teenage girl in Seattle and uncover a web of secrets and lies in this tense and moody crime drama."),
("boardwalk_empire", "Boardwalk Empire", "Atlantic City during Prohibition is home to a colorful cast of gangsters, politicians, and ordinary people trying to make their way in the world.")